# 行列の基礎

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

#### ＊ esc + m == Markdown に切り替え

In [3]:
import numpy as np

In [7]:
# ベクトルの定義
x = np.array([[1],[2],[3]]) # [[]] を二重化して書く
x

array([[1],
       [2],
       [3]])

In [8]:
print(x) # print すると書式を綺麗にできる

[[1]
 [2]
 [3]]


In [9]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [12]:
# 転置
Xt = X.T # numpy の .T メソッドで転置。Xt を転置をしたことを示す関数とする
print(Xt)

[[1 3]
 [2 4]]


In [16]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X) # numpy の中の .linalg の中に .inv(), i.e., inverse がある
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
# 行列積
XX_inv = np.dot(X, X_inv) # .dot(matrix1, matrix2) で martix1 と martix2 の行列積を計算
print(XX_inv) # 厳密ではないが、[1 0; 0 1] の単位行列になっていることがわかる

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い

In [22]:
x = np.array([1, 2, 3]) # [] 一重角括弧でもベクトル自体は作れる
x

array([1, 2, 3])

In [23]:
x.T # 転置をするとうまくできないケースがある

array([1, 2, 3])

In [28]:
x = np.array([[1, 2, 3]])
x

array([[1, 2, 3]])

In [29]:
x.T

array([[1],
       [2],
       [3]])

In [30]:
x = np.array([[1], [2], [3]])

In [31]:
x

array([[1],
       [2],
       [3]])

# Numpy でよく使う処理

In [32]:
X

array([[1, 2],
       [3, 4]])

In [33]:
X.shape # 行と列の番号が取れる

(2, 2)

In [34]:
row, col = X.shape

In [35]:
row

2

In [36]:
col

2

In [38]:
X = np.array([
    [2, 3, 4], # 1 件目
    [1, 2 ,3] # 2 件目
])

In [39]:
print(X)

[[2 3 4]
 [1 2 3]]


In [40]:
X.shape

(2, 3)

In [41]:
row, col = X.shape # 行、列用にそれぞれ変数を準備

In [42]:
row # 行を出力

2

In [43]:
col # 列を出力

3

In [45]:
for x in X:
    print(x) # 行ごとに print
    print('- - ') # 境目のマーク

[2 3 4]
- - 
[1 2 3]
- - 


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5\\
1 & 3 & 4\\
1 & 5 & 9\\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ の時

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- Step 1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- Step 2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step 3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step 4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [71]:
# X の定義
X = np.array([ # np.array([[], [], []])
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [72]:
# y の定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(y)

[[1]
 [5]
 [6]
 [8]]


In [73]:
# X の転置
Xt = X.T

print(Xt)

[[1 1 1 1]
 [2 2 3 5]
 [3 5 4 9]]


In [74]:
# 行列積
XtX = Xt * X

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [75]:
# Step 1
XtX = np.dot(X.T, X) # 行列積には、np.dot() を使用

print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [76]:
# Step 2
XtX_inv = np.linalg.inv(XtX)

print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [77]:
# Step 3
Xty = np.dot(X.T, y)

print(Xty)

[[ 20]
 [ 70]
 [124]]


In [78]:
# Step 4
w = np.dot(XtX_inv, Xty)

print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learn での実装

Python の中で機械学習を実装するためのライブラリ
- Classification
- Regression
- Clustering
- Dimensionality reduction
- Model selection
- Preprocessing

In [80]:
import sklearn 

In [81]:
# Windows でエラーが出た場合
# !pip install scikit-learn

# Mac でエラーが出た場合、
# !pip3 install sckit-learn

# !pip でコマンドプロンプトやターミナルと同じ動き

In [83]:
# 重回帰分析のみ読み込み。不要なものを読み込まないことでメモリを圧迫しないで済む
from sklearn.linear_model import LinearRegression

In [85]:
# モデルの宣言
model = LinearRegression() # LinearRegression を使うと宣言する

In [87]:
# モデルの学習　<-- パラメータの調整
model.fit(X, y) # fit 関数を使うだけ

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [88]:
# 調整後のパラメータの確認。Scikit-learn の場合、ダミーの 1 を行列の左端に入れる必要なし
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [89]:
model.intercept_

array([-0.14285714])

In [95]:
# ダミー変数を入れる場合
# model = LinearRegression()
model = LinearRegression(fit_intercept=False)

In [96]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [97]:
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [98]:
model.intercept_

0.0

In [100]:
# 予測精度 <-- 決定係数 (0 - 1 の範囲で判定)
model.score(X, y) # 0.7 程度あれば初期段階は悪いイメージではない

0.6923076923076924

In [101]:
# 予測値の計算
x = np.array([[1, 2, 3]])

In [103]:
y_pred = model.predict(x) # .predict メソッドで予測値を計算
y_pred

array([[3.]])